Adds a target to .netstandard 2.0
Philo/cake-gulp pull request #27
Opened 2018-10-01 08:04 UTC by theramis

Fixes issue https://github.com/cake-contrib/Cake.Gulp/issues/24

Also updated current support from .net46 to .net461

2018-10-01 08:12 UTC, theramis commented
Not sure why the build is failing. 
![spongebob-squarepants-sad-OPU6wzx8JrHna](https://media3.giphy.com/media/OPU6wzx8JrHna/giphy.gif?cid=e1bb72ff5bb1d6eb4d4a71697756554d)

2018-10-01 10:33 UTC, gep13 commented
@theramis does the build work locally for you?

2018-10-01 10:34 UTC, gep13 commented
Can I get you to try adding this:

https://github.com/cake-contrib/Cake.Gem/blob/develop/.appveyor.yml#L1-L4

To the appveyor.yml file?

2018-10-01 10:44 UTC, theramis commented
Replicated the issue locally, looking into it now

2018-10-01 21:24 UTC, pascalberger requested changes
@theramis Thanks for your contribution 👍 

I've added some comments for some minor fixes which should be done before merging. Are you in a position to make these?

2018-10-01 21:24 UTC, pascalberger commented on src/Cake.Gulp/Cake.Gulp.csproj
> +    <PackageReference Include="Cake.Core" Version="0.30.0">
As this addin doesn't require anything from 0.28+ there's no need to bump this version and it should be compile against 0.28.0 to provide maximum compatibility.

2018-10-01 21:24 UTC, pascalberger commented on src/Cake.Gulp.Tests/Cake.Gulp.Tests.csproj
> +    <PackageReference Include="Cake.Testing" Version="0.30.0" />
As this addin doesn't require anything from 0.28+ there's no need to bump this version and it should be compile against 0.28.0 to provide maximum compatibility.

2018-10-01 21:24 UTC, pascalberger commented on src/Cake.Gulp.Tests/Cake.Gulp.Tests.csproj
> +    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
Should be on the same version as XUnit (2.4.0)

2018-10-01 21:24 UTC, pascalberger commented on src/Cake.Gulp.Tests/Cake.Gulp.Tests.csproj
> +    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
Should be on the same version as XUnit (2.4.0)

2018-10-02 07:52 UTC, theramis commented
Done @pascalberger 
😄

2018-10-02 08:07 UTC, theramis commented
On second thought, after reading this https://xunit.github.io/releases/2.4. Turns out `dotnet-xunit` is not stable so decided to remove it.

2018-10-02 11:03 UTC, merged

2018-10-02 11:04 UTC, pascalberger commented
@theramis Thanks 👍 Your changes have been merged and I'll push a new release containing these changes soon